export const ImagesData = [
  {
    srcUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-02.jpg?customize=template',
    previewUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-02.jpg?customize=template',
  },
  {
    srcUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-03.jpg?customize=template',
    previewUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-03.jpg?customize=template',
  },
  {
    srcUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-04.jpg?customize=template',
    previewUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-04.jpg?customize=template',
  },
  {
    srcUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/07/gallery-02-free-img.jpg',
    previewUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/07/gallery-02-free-img.jpg',
  },
  {
    srcUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/07/gallery-03-free-img.jpg',
    previewUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/07/gallery-03-free-img.jpg',
  },
  {
    srcUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-03.jpg?customize=template',
    previewUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-03.jpg?customize=template',
  },
  {
    srcUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-04.jpg?customize=template',
    previewUrl:
      'https://websitedemos.net/wedding-organizer-04/wp-content/uploads/sites/454/2019/11/pic-04.jpg?customize=template',
  },
];
